### ISSUE TITLE
Подсветка тега «Фейк»

### ISSUE THREAD

**Issue by AngReload** [Staremang/New-Pikabu-Design#3]
Добавьте, пожалуйста, подсветку тега 'фейк'. Этот тег ставят модераторы.
```css
a.story__tag[href="http://pikabu.ru/tag/%F4%E5%E9%EA/hot"] {
  color: #fff;
  background: #ef5350;
  border-color: #b71c1c;
}
```
